site_name: JEAM
site_author: Amir Hosein Hadian
site_description: Evidence Accumulation Models of Continuous Judgments (JEAM) - documentation
repo_name: AmirHoseinHadian/JEAM
repo_url: https://github.com/AmirHoseinHadian/JEAM
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.highlight
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - header.autohide
    - announce.dismiss
    - navigation.expand
  font:
    text: Inter
    code: JetBrains Mono

nav:
  - Home: index.md
  - Usage: usage.md
  - Installation: installation.md
  - Tutorials:
      - Quickstart: tutorials/quickstart.md
      - Design Specification: tutorials/design_spesification.md
      - Mixture Models: tutorials/mixture_models.md
      - Custom Mapping Function: tutorials/custom_mapping_function.md
      - Collapsing Threshold Models: tutorials/collapsing_threshold_models.md
  - API Reference: api.md


plugins:
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            show_source: true
            show_signature_annotations: true
            merge_init_into_class: true
            docstring_style: numpy
            docstring_section_style: table

markdown_extensions:
  - admonition
  - tables
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - javascripts/katex.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
  - stylesheets/extra.css

